name: Pack
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./pack.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: babric b1.7.3.zip
          path: ./babric b1.7.3.zip
